import html2pdf from 'html2pdf.js';

interface ProjectIdea {
    title: string;
    description: string;
    technologies: string[];
    difficulty: string;
    // Add other fields if necessary based on your ProjectIdea interface
}

/**
 * Exports the project idea to a PDF file.
 * @param elementId The ID of the HTML element to render as PDF.
 * @param fileName The name of the file to save.
 */
export const exportToPDF = (elementId: string, fileName: string) => {
    const element = document.getElementById(elementId);
    if (!element) {
        console.error(`Element with id ${elementId} not found`);
        return;
    }

    const opt = {
        margin: 1,
        filename: fileName,
        image: { type: 'jpeg' as const, quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'in' as const, format: 'letter' as const, orientation: 'portrait' as const }
    };

    html2pdf().set(opt).from(element).save();
};

/**
 * Generates a Markdown string from the project idea.
 * @param idea The project idea object.
 * @returns A formatted Markdown string.
 */
export const generateMarkdown = (idea: ProjectIdea): string => {
    return `
# ${idea.title}

## Description
${idea.description}

## Difficulty
**${idea.difficulty}**

## Technologies
${idea.technologies.map(tech => `- ${tech}`).join('\n')}

---
*Generated by Pideas*
`.trim();
};

/**
 * Triggers a download of the Markdown file.
 * @param content The markdown content.
 * @param fileName The name of the file to save.
 */
export const downloadMarkdown = (content: string, fileName: string) => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};
